# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Liikevoima
email: info@liikevoima.fi
description: > # ddd
  LiikeVoima on vuonna 2014 perustettu toiminnalliseen ja ryhmäliikuntaan keskittyvä kuntokeskus. Meille liikunnan ilo ja
  asiakkaidemme tyytyväisyys on ykkösasia. 
old_description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://liikevoima.github.io" # the base hostname & protocol for your site
twitter_username: liikevoima
instagram_username: liikevoima
facebook_username: liikevoimaoy
paginate: 5
paginate_path: "/page:num/"

# Build settings
markdown: kramdown

authors:
  matt:
    display_name: Matt Hackett
    gravatar: 60fd5218fff6927c0ed376cce01c5460
    email: matt@lostdecadegames.com
    web: http://www.richtaur.com/
    twitter: richtaur
    github: richtaur
  geoff:
    display_name: Geoff Blair
    gravatar: 76dbcc74021b8039f14c7b583978b56d
    email: geoff@lostdecadegames.com
    web: http://www.geoffblair.com/
    twitter: geoffblair
    github: geoffb

# permalink: /blog/:title.html